languageCode: "en-us"
baseUrl: ""
title: "SciVis Contest 2021"
theme: "anubis"
paginate: 10
# disqusShortname: yourdiscussshortname
# googleAnalytics: UA-123-45
enableRobotsTXT: true

menu:
  main:
  # - identifier: data
  #   name: Data
  #   title: Data
  #   url: /data/
  #   weight: 2
  - identifier: previous
    name: Previous Contests
    title: Previous Contests
    url: /previous/
    weight: 3
  - identifier: contact
    name: "📬"
    title: Contact
    url: /contact/
    weight: 4

params:
  author: ""
  description: ""
  images:
    - images/og-featured.png # relative path to "static" directory
  customCSS:
    - css/my.css # relative path to "static" directory
  customJS:
    - js/main.js # relative path to "static" directory
  dateFormat: "2006-01-02"
  paginationSinglePost: true
  style: light-without-switcher

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown
